"use client";
import { useState, useMemo, useRef, useEffect } from "react";
import { useQuery, useMutation } from "convex/react";
import { api } from "../../../convex/_generated/api";
import ItineraryPhotos from "./ItineraryPhotos";
import ItineraryComments from "./ItineraryComments";

const CATEGORIES = [
  { id: "food", label: "음식", emoji: "🍜" },
  { id: "cafe", label: "카페", emoji: "☕" },
  { id: "attraction", label: "관광", emoji: "🏛️" },
  { id: "shopping", label: "쇼핑", emoji: "🛍️" },
  { id: "transport", label: "교통", emoji: "🚌" },
  { id: "accommodation", label: "숙소", emoji: "🏨" },
  { id: "other", label: "기타", emoji: "📌" },
];

function getDaysBetween(start: string, end: string) {
  const days: { dayNumber: number; date: string; weekday: string }[] = [];
  const s = new Date(start);
  const e = new Date(end);
  let n = 1;
  while (s <= e) {
    const dateStr = s.toISOString().split("T")[0];
    const weekday = s.toLocaleDateString("ko-KR", { weekday: "short" });
    days.push({ dayNumber: n, date: dateStr, weekday });
    s.setDate(s.getDate() + 1);
    n++;
  }
  return days;
}

function formatShortDate(dateStr: string) {
  const d = new Date(dateStr);
  return `${d.getMonth() + 1}.${d.getDate()}`;
}

function TimePicker({ value, onChange }: { value: string; onChange: (v: string) => void }) {
  const isPM = value ? parseInt(value.split(":")[0]) >= 12 : false;
  const ampm = value ? (isPM ? "PM" : "AM") : "PM";
  let h = value ? parseInt(value.split(":")[0]) : 12;
  if (h > 12) h -= 12;
  if (h === 0) h = 12;
  const m = value ? value.split(":")[1] : "00";

  const handleChange = (newAmpm: string, newH: number, newM: string) => {
    let hour = newH;
    if (newAmpm === "PM" && hour < 12) hour += 12;
    if (newAmpm === "AM" && hour === 12) hour = 0;
    onChange(`${hour.toString().padStart(2, "0")}:${newM}`);
  };

  return (
    <div style={{ display: "flex", gap: 4, alignItems: "center" }}>
      <select className="input" style={{ width: "auto", padding: "3px 6px", fontSize: "0.78rem" }} value={ampm} onChange={e => handleChange(e.target.value, h, m)}>
        <option value="AM">오전</option>
        <option value="PM">오후</option>
      </select>
      <select className="input" style={{ width: "auto", padding: "3px 6px", fontSize: "0.78rem" }} value={h} onChange={e => handleChange(ampm, parseInt(e.target.value), m)}>
        {[1,2,3,4,5,6,7,8,9,10,11,12].map(num => <option key={num} value={num}>{num}</option>)}
      </select>
      <span>:</span>
      <select className="input" style={{ width: "auto", padding: "3px 6px", fontSize: "0.78rem" }} value={m} onChange={e => handleChange(ampm, h, e.target.value)}>
        {["00","10","20","30","40","50"].map(num => <option key={num} value={num}>{num}</option>)}
      </select>
    </div>
  );
}

export default function ItineraryTab({ trip, nickname }: { trip: any; nickname: string }) {
  const days = useQuery(api.itinerary.listDaysByTrip, { tripId: trip._id });
  const allItems = useQuery(api.itinerary.listItemsByTrip, { tripId: trip._id });
  const savedPlaces = useQuery(api.places.listPlacesByTrip, { tripId: trip._id });
  const accommodations = useQuery(api.accommodations.listByTrip, { tripId: trip._id });
  const addDay = useMutation(api.itinerary.addDay);
  const removeDay = useMutation(api.itinerary.removeDay);
  const updateDay = useMutation(api.itinerary.updateDay);
  const addItem = useMutation(api.itinerary.addItem);
  const updateItem = useMutation(api.itinerary.updateItem);
  const removeItem = useMutation(api.itinerary.removeItem);

  const [expandedDays, setExpandedDays] = useState<Set<string>>(new Set());
  const [focusedDayId, setFocusedDayId] = useState<string | null>(null);
  const [dragItem, setDragItem] = useState<any>(null);
  const [dragOverItem, setDragOverItem] = useState<any>(null);
  const [reorderItem, setReorderItem] = useState<string | null>(null);
  const [showPlaceModal, setShowPlaceModal] = useState<string | null>(null);
  const [placeForm, setPlaceForm] = useState({ name: "", category: "attraction", address: "", time: "", lat: undefined as number|undefined, lng: undefined as number|undefined });
  const [placeTab, setPlaceTab] = useState<"saved" | "search">("saved");
  const [editingTime, setEditingTime] = useState<string | null>(null);
  const [editTimeVal, setEditTimeVal] = useState("");
  const [editingMemo, setEditingMemo] = useState<string | null>(null);
  const [editMemoVal, setEditMemoVal] = useState("");
  const [editPlaceModal, setEditPlaceModal] = useState<any | null>(null);
  const [editingPlace, setEditingPlace] = useState<string | null>(null);
  const [editPlaceForm, setEditPlaceForm] = useState({ name: "", category: "attraction" });
  const [saving, setSaving] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const searchInputRef = useRef<HTMLInputElement>(null);
  const mapRef = useRef<HTMLDivElement>(null);
  const [mapInstance, setMapInstance] = useState<any>(null);
  const markersRef = useRef<any[]>([]);
  const polylineRefs = useRef<any[]>([]);
  const myLocationMarkerRef = useRef<any>(null);
  const lastPosRef = useRef<{lat: number, lng: number} | null>(null);

  const [reorderDayId, setReorderDayId] = useState<string | null>(null);

  const tripDays = useMemo(() => getDaysBetween(trip.startDate, trip.endDate), [trip.startDate, trip.endDate]);
  const existingDayNumbers = useMemo(() => new Set(days?.map(d => d.dayNumber) || []), [days]);

  const combinedSavedPlaces = useMemo(() => {
    const list: any[] = [];
    if (accommodations) {
      accommodations.forEach(a => list.push({
        _id: a._id,
        name: a.name,
        address: a.address,
        lat: a.lat,
        lng: a.lng,
        category: "accommodation" // 숙소용 카테고리로 매핑
      }));
    }
    if (savedPlaces) {
      savedPlaces.forEach(p => list.push(p));
    }
    return list;
  }, [savedPlaces, accommodations]);

  // DAY 자동 생성
  useEffect(() => {
    if (days !== undefined && days.length === 0 && tripDays.length > 0 && !saving && !hasAutoGenerated) {
      setHasAutoGenerated(true);
      handleGenerateAllDays();
    }
  }, [days, tripDays.length, saving, hasAutoGenerated]);

  // 첫 번째 DAY 자동 확장
  useEffect(() => {
    if (days && days.length > 0 && expandedDays.size === 0 && !focusedDayId) {
      setExpandedDays(new Set([days[0]._id]));
    }
  }, [days]);

  // 구글 맵 초기화 및 장소 검색 자동완성
  useEffect(() => {
    const apiKey = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;
    if (!apiKey) return;

    function initMapAndAutocomplete() {
      const google = (window as any).google;
      if (!google?.maps) return;

      // 1. 일정 상단 지도 초기화
      if (mapRef.current && !mapInstance) {
        const map = new google.maps.Map(mapRef.current, {
          center: { lat: 37.5, lng: 127 },
          zoom: 12,
          gestureHandling: "greedy",
          fullscreenControl: false,
          streetViewControl: false,
          mapTypeControl: false,
        });
        setMapInstance(map);
      }

      // 2. 모달 내 장소 검색 자동완성
      if ((showPlaceModal && placeTab === "search" || editPlaceModal) && searchInputRef.current) {
        if (google.maps.places) {
          const ac = new google.maps.places.Autocomplete(searchInputRef.current, {
            fields: ["name", "formatted_address", "geometry"]
          });
          ac.addListener("place_changed", () => {
            const place = ac.getPlace();
            if (!place.geometry || !place.geometry.location) return;
            setPlaceForm(f => ({
              ...f,
              name: place.name || f.name,
              address: place.formatted_address || f.address,
              lat: place.geometry.location.lat(),
              lng: place.geometry.location.lng(),
            }));
          });
        }
      }
    }

    if ((window as any).google) {
      initMapAndAutocomplete();
    } else {
      const script = document.createElement("script");
      script.src = `https://maps.googleapis.com/maps/api/js?key=${apiKey}&libraries=places`;
      script.async = true;
      script.onload = initMapAndAutocomplete;
      document.head.appendChild(script);
    }
  }, [showPlaceModal, placeTab, editPlaceModal, mapInstance, days]);

  // 내 위치 실시간 추적 (일정 탭 지도용)
  useEffect(() => {
    if (!mapInstance || !navigator.geolocation) return;
    const watchId = navigator.geolocation.watchPosition((pos) => {
      const { latitude: lat, longitude: lng } = pos.coords;
      lastPosRef.current = { lat, lng };
      const google = (window as any).google;
      if (!google?.maps) return;

      if (!myLocationMarkerRef.current) {
        myLocationMarkerRef.current = new google.maps.Marker({
          position: { lat, lng },
          map: mapInstance,
          title: "내 위치",
          icon: {
            path: google.maps.SymbolPath.CIRCLE,
            fillColor: "#4285F4",
            fillOpacity: 1,
            scale: 8,
            strokeColor: "white",
            strokeWeight: 2,
          },
          zIndex: 999
        });
      } else {
        myLocationMarkerRef.current.setPosition({ lat, lng });
      }
    }, (err) => console.warn("GPS watch failed", err), { enableHighAccuracy: true });

    return () => {
      navigator.geolocation.clearWatch(watchId);
      if (myLocationMarkerRef.current) {
        myLocationMarkerRef.current.setMap(null);
        myLocationMarkerRef.current = null;
      }
    };
  }, [mapInstance]);

  // 지도 마커 및 경로 렌더링
  useEffect(() => {
    if (!mapInstance || allItems === undefined || days === undefined) return;
    const google = (window as any).google;

    // 기존 마커 및 선 지우기
    markersRef.current.forEach(m => m.setMap(null));
    markersRef.current = [];
    polylineRefs.current.forEach(p => p.setMap(null));
    polylineRefs.current = [];

    if (days.length === 0) return;

    // 확장된 모든 DAY + 현재 포커스된 DAY의 장소를 지도에 표시 (모두 닫혀있다면 1일차 표시)
    let targetDayIdsArray = Array.from(expandedDays);
    if (focusedDayId && !targetDayIdsArray.includes(focusedDayId)) {
      targetDayIdsArray.push(focusedDayId);
    }
    const targetDayIds = targetDayIdsArray.length > 0 ? targetDayIdsArray : (days.length > 0 ? [days[0]._id] : []);

    const bounds = new google.maps.LatLngBounds();
    const focusBounds = new google.maps.LatLngBounds();
    const path: any[] = [];
    let placeCount = 0;
    let focusPlaceCount = 0;

    // 날짜 순서대로 정렬해서 경로 그리기
    const sortedTargetDays = targetDayIds.sort((a: any, b: any) => {
      const dayA = days.find(d => d._id === a)?.dayNumber || 0;
      const dayB = days.find(d => d._id === b)?.dayNumber || 0;
      return dayA - dayB;
    });

    sortedTargetDays.forEach((dayId) => {
      const dayItems = (allItems || []).filter((it: any) => it.dayId === dayId).sort((a: any, b: any) => a.orderIndex - b.orderIndex);
      const places = dayItems.filter((it: any) => it.type === "place" && it.placeLat && it.placeLng);
      const dayPath: any[] = [];
      
      places.forEach((p: any, idx: number) => {
        placeCount++;
        const pos = { lat: p.placeLat, lng: p.placeLng };
        dayPath.push(pos);
        bounds.extend(pos);
        if (dayId === focusedDayId) {
          focusBounds.extend(pos);
          focusPlaceCount++;
        }

        const marker = new google.maps.Marker({
          position: pos,
          map: mapInstance,
          label: { text: (idx + 1).toString(), color: "white", fontWeight: "bold", fontSize: "12px" },
          icon: {
            path: google.maps.SymbolPath.CIRCLE,
            fillColor: "#6366f1",
            fillOpacity: 1,
            strokeColor: "white",
            strokeWeight: 2,
            scale: 12
          }
        });
        markersRef.current.push(marker);
      });

      // 날짜별 개별 경로 그리기 (날짜 간 연결되지 않도록)
      if (dayPath.length > 1) {
        const poly = new google.maps.Polyline({
          path: dayPath,
          geodesic: true,
          strokeColor: "#6366f1",
          strokeOpacity: 0.8,
          strokeWeight: 3,
          icons: [{ icon: { path: google.maps.SymbolPath.FORWARD_CLOSED_ARROW }, offset: "50%" }],
          map: mapInstance
        });
        polylineRefs.current.push(poly);
      }
    });

    if (placeCount === 0) return;

    if (focusPlaceCount > 0) {
      if (focusPlaceCount === 1) {
        mapInstance.setCenter({ lat: focusBounds.getNorthEast().lat(), lng: focusBounds.getNorthEast().lng() });
        mapInstance.setZoom(15);
      } else {
        mapInstance.fitBounds(focusBounds);
        const listener = google.maps.event.addListener(mapInstance, "idle", () => {
          if (mapInstance.getZoom() > 15) mapInstance.setZoom(15);
          google.maps.event.removeListener(listener);
        });
      }
    } else {
      mapInstance.fitBounds(bounds);
      const listener = google.maps.event.addListener(mapInstance, "idle", () => {
        if (mapInstance.getZoom() > 15) mapInstance.setZoom(15);
        google.maps.event.removeListener(listener);
      });
    }
  }, [mapInstance, allItems, expandedDays, days, focusedDayId]);

  function toggleDay(dayId: string) {
    setExpandedDays(prev => {
      const n = new Set(prev);
      if (n.has(dayId)) {
        n.delete(dayId);
      } else {
        n.add(dayId);
        setFocusedDayId(dayId);
      }
      return n;
    });
  }

  async function handleGenerateAllDays() {
    setSaving(true);
    for (const td of tripDays) {
      if (!existingDayNumbers.has(td.dayNumber)) {
        await addDay({ tripId: trip._id, dayNumber: td.dayNumber, date: td.date });
      }
    }
    setSaving(false);
  }

  function getItemsForDay(dayId: string) {
    return (allItems || []).filter((it: any) => it.dayId === dayId).sort((a: any, b: any) => a.orderIndex - b.orderIndex);
  }

  async function handleAddPlace(dayId: string) {
    if (!placeForm.name.trim()) return;
    setSaving(true);
    const items = getItemsForDay(dayId);
    let lat = placeForm.lat;
    let lng = placeForm.lng;
    const apiKey = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;
    
    if (apiKey && placeForm.name && (lat === undefined || lng === undefined)) {
      try {
        const q = encodeURIComponent(`${placeForm.name} ${placeForm.address || trip.destination}`);
        const res = await fetch(`https://maps.googleapis.com/maps/api/geocode/json?address=${q}&key=${apiKey}`);
        const data = await res.json();
        if (data.results?.[0]) {
          lat = data.results[0].geometry.location.lat;
          lng = data.results[0].geometry.location.lng;
        }
      } catch (e) { /* ignore */ }
    }
    
    await addItem({
      dayId: dayId as any, tripId: trip._id, orderIndex: items.length,
      type: "place", placeName: placeForm.name.trim(), placeCategory: placeForm.category,
      placeAddress: placeForm.address || undefined, placeLat: lat, placeLng: lng,
      time: placeForm.time || undefined,
    });
    setPlaceForm({ name: "", category: "attraction", address: "", time: "", lat: undefined, lng: undefined });
    setShowPlaceModal(null);
    setSaving(false);
  }

  async function handleAddSavedPlace(dayId: string, place: any) {
    const items = getItemsForDay(dayId);
    await addItem({
      dayId: dayId as any, tripId: trip._id, orderIndex: items.length,
      type: "place", placeName: place.name, placeCategory: place.category,
      placeAddress: place.address, placeLat: place.lat, placeLng: place.lng,
      placeMapLink: place.mapLink,
    });
    setShowPlaceModal(null);
  }

  async function handleSaveTime(itemId: string) {
    await updateItem({ itemId: itemId as any, time: editTimeVal || undefined });
    setEditingTime(null);
  }

  async function handleSaveMemo(itemId: string) {
    await updateItem({ itemId: itemId as any, memo: editMemoVal || undefined });
    setEditingMemo(null);
  }

  async function handleMoveItem(item: any, direction: "up" | "down", dayItems: any[]) {
    const idx = dayItems.findIndex((i: any) => i._id === item._id);
    const swapIdx = direction === "up" ? idx - 1 : idx + 1;
    if (swapIdx < 0 || swapIdx >= dayItems.length) return;
    const other = dayItems[swapIdx];
    await updateItem({ itemId: item._id, orderIndex: other.orderIndex });
    await updateItem({ itemId: other._id, orderIndex: item.orderIndex });
  }

  // 드래그 앤 드롭으로 순서 변경
  async function handleDragDrop(dayItems: any[]) {
    if (!dragItem || !dragOverItem || dragItem._id === dragOverItem._id) return;
    const dragIdx = dayItems.findIndex((i: any) => i._id === dragItem._id);
    const dropIdx = dayItems.findIndex((i: any) => i._id === dragOverItem._id);
    if (dragIdx < 0 || dropIdx < 0) return;
    await updateItem({ itemId: dragItem._id, orderIndex: dayItems[dropIdx].orderIndex });
    await updateItem({ itemId: dayItems[dropIdx]._id, orderIndex: dayItems[dragIdx].orderIndex });
    setDragItem(null);
    setDragOverItem(null);
  }

  async function moveItemUp(itemId: string, dayId: string) {
    const dayItems = (allItems || []).filter((it: any) => it.dayId === dayId).sort((a: any, b: any) => a.orderIndex - b.orderIndex);
    const idx = dayItems.findIndex((i: any) => i._id === itemId);
    if (idx > 0) {
      const current = dayItems[idx];
      const prev = dayItems[idx - 1];
      const targetOrder = prev.orderIndex - 0.001;
      await updateItem({ itemId: current._id, orderIndex: targetOrder });
    }
    // setReorderItem(null); // 메뉴 유지
  }

  async function moveItemDown(itemId: string, dayId: string) {
    const dayItems = (allItems || []).filter((it: any) => it.dayId === dayId).sort((a: any, b: any) => a.orderIndex - b.orderIndex);
    const idx = dayItems.findIndex((i: any) => i._id === itemId);
    if (idx < dayItems.length - 1) {
      const current = dayItems[idx];
      const next = dayItems[idx + 1];
      const targetOrder = next.orderIndex + 0.001;
      await updateItem({ itemId: current._id, orderIndex: targetOrder });
    }
    // setReorderItem(null); // 메뉴 유지
  }

  if (days === undefined || allItems === undefined) {
    return <div style={{ textAlign: "center", padding: 60 }}><span className="spinner" style={{ margin: "0 auto", width: 32, height: 32 }} /></div>;
  }

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      {/* 텍스트와 지도를 포함하는 Sticky 컨테이너 */}
      <div style={{ position: "sticky", top: 0, zIndex: 50, display: "flex", flexDirection: "column", gap: 12, background: "rgba(255,255,255,0.75)", backdropFilter: "blur(12px)", paddingTop: 16, paddingBottom: 16, margin: "0 -20px", paddingLeft: 20, paddingRight: 20 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <h2 style={{ fontWeight: 900, fontSize: "1.2rem", letterSpacing: "-0.02em" }}>🗓️ 일정</h2>
        </div>

        {/* 상단 지도 영역 (경로 표시) */}
        <div className="glass" style={{ borderRadius: 20, overflow: "hidden", height: 200, flexShrink: 0, border: "2px solid rgba(0,0,0,0.08)", position: "relative" }}>
          <div ref={mapRef} style={{ width: "100%", height: "100%" }} />
          {!mapInstance && (
            <div style={{ position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyContent: "center", background: "#f8fafc", color: "var(--text-muted)", fontSize: "0.85rem" }}>
              지도를 불러오는 중이거나 일정이 없습니다
            </div>
          )}
          {/* 내 위치 버튼 추가 */}
          {mapInstance && (
            <button
              onClick={() => {
                if (lastPosRef.current) {
                  mapInstance.setCenter(lastPosRef.current);
                  mapInstance.setZoom(15);
                } else if (navigator.geolocation) {
                  navigator.geolocation.getCurrentPosition((pos) => {
                    const p = { lat: pos.coords.latitude, lng: pos.coords.longitude };
                    lastPosRef.current = p;
                    mapInstance.setCenter(p);
                    mapInstance.setZoom(15);
                  });
                }
              }}
              style={{
                position: "absolute", bottom: 12, right: 12,
                width: 36, height: 36, borderRadius: "50%",
                background: "#ffffff", border: "1px solid rgba(0,0,0,0.1)",
                boxShadow: "0 2px 10px rgba(66,133,244,0.25)",
                display: "flex", alignItems: "center", justifyContent: "center",
                cursor: "pointer", zIndex: 10, color: "#4285F4"
              }}
              title="내 위치로 이동"
            >
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="8" strokeOpacity="0.4" />
                <circle cx="12" cy="12" r="2" fill="currentColor" stroke="none" />
                <line x1="12" y1="2" x2="12" y2="6" />
                <line x1="12" y1="18" x2="12" y2="22" />
                <line x1="2" y1="12" x2="6" y2="12" />
                <line x1="18" y1="12" x2="22" y2="12" />
              </svg>
            </button>
          )}
        </div>
      </div>

      {days.length === 0 ? (
        <div className="glass" style={{ textAlign: "center", padding: 48, color: "var(--text-muted)" }}>
          <div style={{ fontSize: 48, marginBottom: 12 }}>📅</div>
          <p>아직 일정이 없습니다</p>
          <p style={{ fontSize: "0.8rem", marginTop: 6 }}>여행 기간에 맞춰 일정이 생성되는 중입니다...</p>
        </div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          {days.map((day) => {
            const isExpanded = expandedDays.has(day._id);
            const dayItems = getItemsForDay(day._id);
            const td = tripDays.find(t => t.dayNumber === day.dayNumber);
            return (
              <div key={day._id} className="glass" style={{ overflow: "hidden", border: "2px solid rgba(0,0,0,0.08)", borderRadius: 20 }}>
                {/* DAY 헤더 */}
                <div onClick={() => { 
                  if (!expandedDays.has(day._id)) toggleDay(day._id); 
                  setFocusedDayId(null); // 강제 리트리거를 위해 잠시 해제
                  setTimeout(() => setFocusedDayId(day._id), 0);
                }} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 20px", background: isExpanded ? "var(--sky)" : "transparent", transition: "background 0.2s", cursor: "pointer" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                    <span style={{ fontWeight: 900, fontSize: "1.05rem", color: isExpanded ? "#1a1a1a" : "var(--text-primary)" }}>day {day.dayNumber}</span>
                    <span style={{ fontSize: "0.82rem", color: isExpanded ? "rgba(0,0,0,0.6)" : "var(--text-muted)", fontWeight: 600 }}>
                      {formatShortDate(day.date)}/{td?.weekday || ""}
                    </span>
                    {day.title && <span style={{ fontSize: "0.8rem", color: isExpanded ? "rgba(0,0,0,0.7)" : "var(--text-secondary)", fontWeight: 700 }}>· {day.title}</span>}
                  </div>
                  <div onClick={(e) => { e.stopPropagation(); toggleDay(day._id); }} style={{ display: "flex", alignItems: "center", gap: 8, cursor: "pointer", padding: "4px 8px", borderRadius: 8 }}>
                    <span className="badge badge-sky" style={{ fontSize: "0.65rem", background: "var(--sky)", color: "#1a1a1a", border: isExpanded ? "1px solid rgba(0,0,0,0.1)" : "none" }}>{dayItems.length}개</span>
                    <span style={{ fontSize: 14, color: isExpanded ? "#1a1a1a" : "var(--text-muted)", transition: "transform 0.2s", transform: isExpanded ? "rotate(180deg)" : "rotate(0)" }}>▼</span>
                  </div>
                </div>

                {/* DAY 내용 */}
                {isExpanded && (
                  <div style={{ padding: "0 18px 16px" }}>
                    {/* 항목 타임라인 */}
                    {dayItems.length > 0 && (
                      <div style={{ display: "flex", flexDirection: "column", gap: 0, marginBottom: 12 }}>
                        {dayItems.map((item: any, idx: number) => {
                          const cat = CATEGORIES.find(c => c.id === item.placeCategory);
                          return (
                            <div key={item._id} style={{ display: "flex", gap: 12, position: "relative" }}>
                              {/* 타임라인 라인 */}
                              <div style={{ display: "flex", flexDirection: "column", alignItems: "center", width: 28, flexShrink: 0, paddingTop: 28 }}>
                                <div onClick={() => { if(item.placeLat && item.placeLng && mapInstance) { mapInstance.setCenter({lat: item.placeLat, lng: item.placeLng}); mapInstance.setZoom(17); } }} style={{ width: 24, height: 24, borderRadius: "50%", background: item.type === "place" ? "var(--accent)" : "var(--warning)", color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 800, zIndex: 1, cursor: item.placeLat ? "pointer" : "default" }}>
                                  {idx + 1}
                                </div>
                                {idx < dayItems.length - 1 && (
                                  <div style={{ width: 2, flex: 1, background: "rgba(0,0,0,0.08)", minHeight: 20 }} />
                                )}
                              </div>

                              {/* 항목 카드 */}
                              <div style={{ flex: 1, paddingBottom: 14 }}>
                                <div style={{ background: "#fff", border: "1px solid rgba(0,0,0,0.06)", borderRadius: 12, padding: "12px 14px", boxShadow: "0 1px 3px rgba(0,0,0,0.03)" }}>
                                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
                                    <div style={{ flex: 1 }}>
                                      {/* 시간 */}
                                      {editingTime === item._id ? (
                                        <div style={{ display: "flex", gap: 4, marginBottom: 6 }}>
                                          <TimePicker value={editTimeVal} onChange={setEditTimeVal} />
                                          <button onClick={() => handleSaveTime(item._id)}
                                            style={{ padding: "3px 8px", fontSize: "0.72rem", background: "var(--accent)", color: "#fff", border: "none", borderRadius: 6, cursor: "pointer", whiteSpace: "nowrap" }}>저장</button>
                                          <button onClick={() => setEditingTime(null)}
                                            style={{ padding: "3px 8px", fontSize: "0.72rem", background: "transparent", border: "1px solid rgba(0,0,0,0.1)", borderRadius: 6, cursor: "pointer", whiteSpace: "nowrap" }}>취소</button>
                                        </div>
                                      ) : (
                                        <button onClick={() => { setEditingTime(item._id); setEditTimeVal(item.time || ""); }}
                                          style={{ background: item.time ? "rgba(99,102,241,0.08)" : "rgba(0,0,0,0.03)", border: "none", padding: "2px 8px", borderRadius: 6, fontSize: "0.72rem", color: item.time ? "var(--accent)" : "var(--text-muted)", cursor: "pointer", marginBottom: 6, fontWeight: 600, display: "inline-block" }}>
                                          🕐 {item.time || "시간 추가"}
                                        </button>
                                      )}

                                      {item.type === "place" ? (
                                        <>
                                          <div style={{ display: "flex", alignItems: "center", gap: 6, cursor: item.placeLat ? "pointer" : "default" }} onClick={() => { if(item.placeLat && item.placeLng && mapInstance) { mapInstance.setCenter({lat: item.placeLat, lng: item.placeLng}); mapInstance.setZoom(17); } }}>
                                            <span style={{ fontSize: 16 }}>{cat?.emoji || "📌"}</span>
                                            <span style={{ fontWeight: 700, fontSize: "0.92rem", textDecoration: item.placeLat ? "underline" : "none", textDecorationColor: "rgba(0,0,0,0.15)", textUnderlineOffset: 3 }}>{item.placeName}</span>
                                          </div>
                                          <div style={{ display: "flex", gap: 4, marginTop: 4, flexWrap: "wrap" }}>
                                            <span className="badge badge-purple" style={{ fontSize: "0.62rem" }}>{cat?.label || "기타"}</span>
                                            {item.placeAddress && <span style={{ fontSize: "0.72rem", color: "var(--text-muted)" }}>· {item.placeAddress}</span>}
                                          </div>
                                          
                                          {/* 메모 영역 */}
                                          {editingMemo === item._id ? (
                                            <div style={{ marginTop: 8, display: "flex", gap: 6 }}>
                                              <input className="input" placeholder="메모 입력" value={editMemoVal} onChange={e => setEditMemoVal(e.target.value)} style={{ padding: "4px 8px", fontSize: "0.82rem", minHeight: 28 }} autoFocus onKeyDown={e => e.key === "Enter" && handleSaveMemo(item._id)} />
                                              <button onClick={() => handleSaveMemo(item._id)} style={{ padding: "4px 10px", fontSize: "0.78rem", background: "var(--accent)", color: "#fff", border: "none", borderRadius: 6, cursor: "pointer" }}>저장</button>
                                              <button onClick={() => setEditingMemo(null)} style={{ padding: "4px 10px", fontSize: "0.78rem", background: "transparent", border: "1px solid rgba(0,0,0,0.1)", borderRadius: 6, cursor: "pointer" }}>취소</button>
                                            </div>
                                          ) : item.memo ? (
                                            <div style={{ marginTop: 8, padding: "8px 12px", background: "rgba(245,158,11,0.06)", borderRadius: 8, borderLeft: "3px solid var(--warning)", fontSize: "0.82rem", color: "var(--text-secondary)", lineHeight: 1.4, position: "relative" }}>
                                              {item.memo}
                                              <button onClick={() => { setEditingMemo(item._id); setEditMemoVal(item.memo); }} style={{ position: "absolute", top: 4, right: 4, background: "none", border: "none", fontSize: "0.7rem", color: "var(--text-muted)", cursor: "pointer" }}>✏️</button>
                                            </div>
                                          ) : (
                                            <button onClick={() => { setEditingMemo(item._id); setEditMemoVal(""); }} style={{ marginTop: 8, background: "none", border: "none", fontSize: "0.75rem", color: "var(--text-muted)", cursor: "pointer", display: "flex", alignItems: "center", gap: 4 }}>
                                              <span style={{ fontSize: "0.9rem" }}>📝</span> 메모 추가
                                            </button>
                                          )}
                                        </>
                                      ) : null}
                                    </div>

                                    {/* 액션 버튼 */}
                                    <div style={{ display: "flex", flexDirection: "column", gap: 6, marginLeft: 8, alignItems: "center" }}>
                                      {/* 드래그 및 순서 변경 */}
                                      {(reorderDayId === day._id || reorderItem === item._id) ? (
                                        <div style={{ display: "flex", flexDirection: "column", gap: 6, alignItems: "center", background: "#f1f5f9", padding: "6px 4px", borderRadius: 12, border: "1px solid #e2e8f0" }}>
                                          <button onClick={() => moveItemUp(item._id, day._id)} disabled={idx === 0} style={{ width: 30, height: 30, border: "1px solid #cbd5e1", background: "white", borderRadius: 8, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16, cursor: idx === 0 ? "default" : "pointer", opacity: idx === 0 ? 0.3 : 1, boxShadow: "0 1px 2px rgba(0,0,0,0.05)" }}>↑</button>
                                          <button onClick={() => moveItemDown(item._id, day._id)} disabled={idx === dayItems.length - 1} style={{ width: 30, height: 30, border: "1px solid #cbd5e1", background: "white", borderRadius: 8, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16, cursor: idx === dayItems.length - 1 ? "default" : "pointer", opacity: idx === dayItems.length - 1 ? 0.3 : 1, boxShadow: "0 1px 2px rgba(0,0,0,0.05)" }}>↓</button>
                                          {reorderItem === item._id && !reorderDayId && <button onClick={() => setReorderItem(null)} style={{ border: "none", background: "none", fontSize: 11, cursor: "pointer", color: "var(--text-muted)", marginTop: 2 }}>닫기</button>}
                                        </div>
                                      ) : (
                                        <div
                                          draggable
                                          onDragStart={() => setDragItem(item)}
                                          onDragOver={(e) => { e.preventDefault(); setDragOverItem(item); }}
                                          onDrop={() => handleDragDrop(dayItems)}
                                          onDragEnd={() => { setDragItem(null); setDragOverItem(null); }}
                                          onClick={() => setReorderItem(item._id)}
                                          style={{ width: 36, display: "flex", justifyContent: "center", cursor: "pointer", padding: "4px 0", fontSize: 20, color: "var(--accent)", lineHeight: 1, userSelect: "none", touchAction: "none" }}
                                          title="클릭하여 순서 변경"
                                        >⇅</div>
                                      )}
                                      
                                      {/* 편집 버튼 */}
                                      {item.type === "place" && reorderItem !== item._id && (
                                        <button onClick={() => {
                                          setEditPlaceModal(item);
                                          setPlaceForm({
                                            name: item.placeName || "", category: item.placeCategory || "attraction",
                                            address: item.placeAddress || "", time: item.time || "",
                                            lat: item.placeLat, lng: item.placeLng
                                          });
                                        }} style={{ width: 36, display: "flex", justifyContent: "center", background: "rgba(99,102,241,0.06)", border: "1px solid rgba(99,102,241,0.15)", borderRadius: 6, cursor: "pointer", fontSize: 11, color: "var(--accent)", padding: "5px 0", lineHeight: 1, transition: "all 0.15s", whiteSpace: "nowrap", fontWeight: 700 }}>편집</button>
                                      )}
                                      {/* 삭제 버튼 */}
                                      {reorderItem !== item._id && (
                                        <button onClick={() => removeItem({ itemId: item._id })}
                                          style={{ width: 36, display: "flex", justifyContent: "center", background: "rgba(239,68,68,0.06)", border: "1px solid rgba(239,68,68,0.15)", borderRadius: 6, cursor: "pointer", fontSize: 14, color: "var(--danger)", padding: "4px 0", lineHeight: 1, transition: "all 0.15s" }}>✕</button>
                                      )}
                                    </div>
                                  </div>

                                  {/* 사진 */}
                                  <ItineraryPhotos item={item} nickname={nickname} />
                                </div>
                              </div>
                            </div>
                          );
                        })}
                      </div>
                    )}

                    {/* 추가 버튼 */}
                    <div style={{ display: "flex", gap: 8 }}>
                      <button onClick={() => { setShowPlaceModal(day._id); setPlaceTab("saved"); }}
                        style={{ flex: 1, padding: "10px", border: "1px dashed rgba(0,0,0,0.15)", borderRadius: 10, background: "#fafafa", cursor: "pointer", fontSize: "0.82rem", fontWeight: 600, color: "var(--text-secondary)", transition: "all 0.15s" }}
                        onMouseEnter={e => e.currentTarget.style.borderColor = "var(--accent)"}
                        onMouseLeave={e => e.currentTarget.style.borderColor = "rgba(0,0,0,0.15)"}>
                        + 장소 추가
                      </button>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* 장소 추가 모달 */}
      {showPlaceModal && (
        <div className="modal-overlay" onClick={() => setShowPlaceModal(null)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <h3 style={{ fontWeight: 700, fontSize: "1.1rem", marginBottom: 16 }}>📍 장소 추가</h3>
            <div style={{ display: "flex", gap: 6, marginBottom: 16 }}>
              <button onClick={() => setPlaceTab("saved")}
                className={`badge ${placeTab === "saved" ? "badge-purple" : ""}`}
                style={{ cursor: "pointer", padding: "6px 14px", fontSize: "0.82rem", background: placeTab !== "saved" ? "rgba(0,0,0,0.04)" : undefined }}>
                📌 저장된 장소
              </button>
              <button onClick={() => setPlaceTab("search")}
                className={`badge ${placeTab === "search" ? "badge-purple" : ""}`}
                style={{ cursor: "pointer", padding: "6px 14px", fontSize: "0.82rem", background: placeTab !== "search" ? "rgba(0,0,0,0.04)" : undefined }}>
                🔍 직접 입력
              </button>
            </div>

            {placeTab === "saved" ? (
              <div style={{ maxHeight: 350, overflowY: "auto" }}>
                {combinedSavedPlaces.length === 0 ? (
                  <div style={{ textAlign: "center", padding: 32, color: "var(--text-muted)", fontSize: "0.85rem" }}>
                    <p>저장된 장소나 숙소가 없습니다.</p>
                    <p style={{ marginTop: 4, fontSize: "0.78rem" }}>예약 또는 지도 탭에서 정보를 먼저 추가하거나, 직접 입력을 이용하세요.</p>
                  </div>
                ) : (
                  <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                    {combinedSavedPlaces.map((p: any) => {
                      // 숙소는 전용 카테고리 기호로 처리
                      const cat = p.category === "accommodation" 
                        ? { emoji: "🏨", label: "숙소" } 
                        : CATEGORIES.find(c => c.id === p.category);
                      return (
                        <div key={p._id} onClick={() => handleAddSavedPlace(showPlaceModal, p)}
                          className="glass-hover" style={{ padding: "10px 14px", borderRadius: 10, cursor: "pointer", border: "1px solid rgba(0,0,0,0.06)", display: "flex", alignItems: "center", gap: 10, background: "#fff" }}>
                          <span style={{ fontSize: 20 }}>{cat?.emoji || "📌"}</span>
                          <div>
                            <div style={{ fontWeight: 600, fontSize: "0.88rem" }}>{p.name}</div>
                            <div style={{ fontSize: "0.72rem", color: "var(--text-muted)" }}>{cat?.label} {p.address ? `· ${p.address}` : ""}</div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            ) : (
              <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
                <div><label>장소 이름 검색 (구글맵 자동완성) *</label><input ref={searchInputRef} className="input" placeholder="예: 도톤보리" value={placeForm.name} onChange={e => setPlaceForm(f => ({ ...f, name: e.target.value }))} /></div>
                <div><label>주소 (선택)</label><input className="input" placeholder="주소 입력" value={placeForm.address} onChange={e => setPlaceForm(f => ({ ...f, address: e.target.value }))} /></div>
                <div><label>시간 (선택)</label><TimePicker value={placeForm.time} onChange={time => setPlaceForm(f => ({ ...f, time }))} /></div>
                <div>
                  <label>카테고리</label>
                  <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
                    {CATEGORIES.map(c => (
                      <button key={c.id} type="button" onClick={() => setPlaceForm(f => ({ ...f, category: c.id }))}
                        style={{ padding: "5px 12px", borderRadius: 20, border: `1px solid ${placeForm.category === c.id ? "var(--accent)" : "rgba(0,0,0,0.08)"}`, background: placeForm.category === c.id ? "var(--accent-dim)" : "transparent", color: placeForm.category === c.id ? "var(--accent)" : "var(--text-secondary)", fontSize: "0.78rem", cursor: "pointer" }}>
                        {c.emoji} {c.label}
                      </button>
                    ))}
                  </div>
                </div>
                <div style={{ display: "flex", gap: 10 }}>
                  <button className="btn-ghost" style={{ flex: 1, justifyContent: "center" }} onClick={() => setShowPlaceModal(null)}>취소</button>
                  <button className="btn-primary" style={{ flex: 1, justifyContent: "center" }} onClick={() => handleAddPlace(showPlaceModal)} disabled={saving || !placeForm.name.trim()}>
                    {saving ? <span className="spinner" /> : "추가"}
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* 장소 수정 모달 */}
      {editPlaceModal && (
        <div className="modal-overlay" onClick={() => setEditPlaceModal(null)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <h3 style={{ fontWeight: 700, fontSize: "1.1rem", marginBottom: 16 }}>📍 장소 수정</h3>
            <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
              <div><label>장소 이름 검색 (구글맵 자동완성) *</label><input ref={searchInputRef} className="input" placeholder="예: 도톤보리" value={placeForm.name} onChange={e => setPlaceForm(f => ({ ...f, name: e.target.value }))} /></div>
              <div><label>주소 (선택)</label><input className="input" placeholder="주소 입력" value={placeForm.address} onChange={e => setPlaceForm(f => ({ ...f, address: e.target.value }))} /></div>
              <div><label>시간 (선택)</label><TimePicker value={placeForm.time} onChange={time => setPlaceForm(f => ({ ...f, time }))} /></div>
              <div>
                <label>카테고리</label>
                <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
                  {CATEGORIES.map(c => (
                    <button key={c.id} type="button" onClick={() => setPlaceForm(f => ({ ...f, category: c.id }))}
                      style={{ padding: "5px 12px", borderRadius: 20, border: `1px solid ${placeForm.category === c.id ? "var(--accent)" : "rgba(0,0,0,0.08)"}`, background: placeForm.category === c.id ? "var(--accent-dim)" : "transparent", color: placeForm.category === c.id ? "var(--accent)" : "var(--text-secondary)", fontSize: "0.78rem", cursor: "pointer" }}>
                      {c.emoji} {c.label}
                    </button>
                  ))}
                </div>
              </div>
              <div style={{ display: "flex", gap: 10 }}>
                <button className="btn-ghost" style={{ flex: 1, justifyContent: "center" }} onClick={() => setEditPlaceModal(null)}>취소</button>
                <button className="btn-primary" style={{ flex: 1, justifyContent: "center" }} onClick={async () => {
                   if (!placeForm.name.trim()) return;
                   setSaving(true);
                   let lat = placeForm.lat;
                   let lng = placeForm.lng;
                   const apiKey = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;
                   if (apiKey && placeForm.name && (lat === undefined || lng === undefined)) {
                     try {
                       const q = encodeURIComponent(`${placeForm.name} ${placeForm.address || trip.destination}`);
                       const res = await fetch(`https://maps.googleapis.com/maps/api/geocode/json?address=${q}&key=${apiKey}`);
                       const data = await res.json();
                       if (data.results?.[0]) {
                         lat = data.results[0].geometry.location.lat;
                         lng = data.results[0].geometry.location.lng;
                       }
                     } catch (e) { /* ignore */ }
                   }
                   await updateItem({ itemId: editPlaceModal._id, placeName: placeForm.name, placeCategory: placeForm.category, placeAddress: placeForm.address || undefined, placeLat: lat, placeLng: lng, time: placeForm.time || undefined });
                   setEditPlaceModal(null);
                   setSaving(false);
                }} disabled={saving || !placeForm.name.trim()}>
                  {saving ? <span className="spinner" /> : "저장"}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
